In [2]:
import numpy as np

# Propiedades y estructura

Antes de operar con un array, es fundamental saber cómo está organizado: cuántas dimensiones tiene, qué forma, cuántos elementos y de que tipo. NumPy expone todos estos datos a través de atributos de ndarray

In [16]:
array = np.array([ [1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

print(array)
print('dimesion', array.shape)
print('numero de dimensiones de la matriz', array.ndim)
print('tipo de dato de los elementos del array', array.dtype)
print('total de elementos', array.size)

[[ 1  2  3  6]
 [ 4  5  6  3]
 [ 7  8  9  2]
 [10 11 12 34]]
dimesion (4, 4)
numero de dimensiones de la matriz 2
tipo de dato de los elementos del array int64
16


### RESHAPE: - cambiar la forma sin cambiar los datos

In [20]:
vector = np.arange(12)
print(vector)

matriz = vector.reshape(3,4)
print(matriz)

matriz2 = vector.reshape(2,2,3)
print(matriz2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### Vista vs Copia

In [31]:
original = np.array([1,2,3,4,5,6,7])

vista = original.reshape(1,7)
copia = original.copy()



original[0] = 99

print(original)
print(vista)
print(copia)

float = original.astype(np.float64)
print(float)




[99  2  3  4  5  6  7]
[[99  2  3  4  5  6  7]]
[1 2 3 4 5 6 7]
[99.  2.  3.  4.  5.  6.  7.]
