# EDA 01 — Análisis de notas de la clase 🎓

**Temas que practicamos:** NumPy 01 al 05 (arrays, creación, propiedades, indexación, operaciones)

---

## Contexto

Eres el profesor de matemáticas de 1º de Bachillerato.  
Tienes las **notas del examen de 25 alumnos** (escala 0–10) y quieres analizarlas con NumPy.

El array ya está preparado para que puedas empezar directamente:

In [36]:
import numpy as np

np.random.seed(42)  # fija la aleatoriedad para obtener siempre los mismos valores
notas = np.round(np.random.uniform(2, 10, size=25), 1)
print("Notas de la clase:", notas)

Notas de la clase: [5.  9.6 7.9 6.8 3.2 3.2 2.5 8.9 6.8 7.7 2.2 9.8 8.7 3.7 3.5 3.5 4.4 6.2
 5.5 4.3 6.9 3.1 4.3 4.9 5.6]


---
## Ejercicio 1 — Conoce tu array

Muestra por pantalla:
- El número total de alumnos
- El tipo de dato del array
- El número de dimensiones

In [37]:
# Tu código aquí
print('Numero de alumnos', notas.size)
print('Tipo de dato del array', notas.dtype)
print('Dimensiones', notas.ndim)

Numero de alumnos 25
Tipo de dato del array float64
Dimensiones 1


---
## Ejercicio 2 — Slicing

Muestra las notas del **alumno 5 al alumno 10** (posiciones 4 a 9, recuerda que Python empieza en 0).

In [38]:
# Tu código aquí
print( notas[4:10] )


[3.2 3.2 2.5 8.9 6.8 7.7]


---
## Ejercicio 3 — Nota más alta, más baja y media

Calcula con NumPy:
- La nota más alta
- La nota más baja
- La nota media de la clase

> Pista: usa `np.max()`, `np.min()` y `np.mean()`

In [39]:
# Tu código aquí
min = np.max(notas)
max = np.min(notas)
media = np.mean(notas)
print(min)
print(max)
print(media)


9.8
2.2
5.528


---
## Ejercicio 4 — Filtrado booleano: aprobados

Crea un array que contenga **solo las notas de los alumnos que han aprobado** (nota >= 5).  
Muestra también cuántos alumnos han aprobado.

In [40]:
# Tu código aquí
aprobados = notas >= 5
print(notas[aprobados])

cantidad = np.sum(aprobados)
print(f"{cantidad} de {len(notas)} aprobados")


[5.  9.6 7.9 6.8 8.9 6.8 7.7 9.8 8.7 6.2 5.5 6.9 5.6]
13 de 25 aprobados


---
## Ejercicio 5 — Operación vectorial: cambio de escala

El director del centro quiere las notas en escala **0–100** (en lugar de 0–10).  
Convierte todo el array multiplicando cada nota por 10.  
Guarda el resultado en una variable llamada `notas_100`.

In [41]:
# Tu código aquí
notas_100 = np.int64(notas * 10)
print(notas_100)


[50 96 79 68 32 32 25 89 68 77 22 98 87 37 35 35 44 62 55 43 69 31 43 49
 56]


---
## Ejercicio 6 — ¿Cuántos superan la media?

Usando el array original `notas` (escala 0–10), calcula cuántos alumnos tienen una nota **estrictamente superior a la media** de la clase.

In [42]:
# Tu código aquí
alumnos_sobre_media = notas[notas > media]
print(len(alumnos_sobre_media))

lista_aprobados = notas > media
print(np.sum(lista_aprobados))


11
11


---
## Ejercicio 7 — Suspensos

Crea un array `suspensos` con las notas de los alumnos que NO han aprobado (nota < 5).  
Muestra cuántos son y sus notas.

In [43]:
# Tu código aquí

suspensos = notas < 5
print(notas[suspensos])

cantidad = np.sum(suspensos)
print(f"{cantidad} de {len(notas)} suspensos")

[3.2 3.2 2.5 2.2 3.7 3.5 3.5 4.4 4.3 3.1 4.3 4.9]
12 de 25 suspensos


---
## Ejercicio 8 — np.where: etiquetas

Usa `np.where()` para crear un array de texto donde:
- Si nota >= 5 → `"Aprobado"`
- Si nota < 5 → `"Suspenso"`

Muestra el resultado junto a las notas originales.

In [44]:
# Tu código aquí
etiquetas = np.where(notas >= 5, 'Aprobado', "Suspenso")

for nota, e in zip(notas, etiquetas):
    print(f"Nota: {nota} → {e}")


Nota: 5.0 → Aprobado
Nota: 9.6 → Aprobado
Nota: 7.9 → Aprobado
Nota: 6.8 → Aprobado
Nota: 3.2 → Suspenso
Nota: 3.2 → Suspenso
Nota: 2.5 → Suspenso
Nota: 8.9 → Aprobado
Nota: 6.8 → Aprobado
Nota: 7.7 → Aprobado
Nota: 2.2 → Suspenso
Nota: 9.8 → Aprobado
Nota: 8.7 → Aprobado
Nota: 3.7 → Suspenso
Nota: 3.5 → Suspenso
Nota: 3.5 → Suspenso
Nota: 4.4 → Suspenso
Nota: 6.2 → Aprobado
Nota: 5.5 → Aprobado
Nota: 4.3 → Suspenso
Nota: 6.9 → Aprobado
Nota: 3.1 → Suspenso
Nota: 4.3 → Suspenso
Nota: 4.9 → Suspenso
Nota: 5.6 → Aprobado


## Resumen de funciones usadas

| Función / Sintaxis | ¿Para qué sirve? |
|---|---|
| `array.size` | Total de elementos |
| `array.dtype` | Tipo de dato |
| `array.ndim` | Número de dimensiones |
| `array[4:10]` | Slicing: elementos del índice 4 al 9 |
| `np.max(a)` / `np.min(a)` | Valor máximo / mínimo |
| `np.mean(a)` | Media aritmética |
| `a[a >= 5]` | Filtrado booleano |
| `a * 10` | Operación vectorial (sin bucles) |
| `np.where(cond, x, y)` | Etiquetas condicionales elemento a elemento |